---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 24474.
--- DateTime: 2022/7/28 22:59
---

const = {}
local map = {}
local meta = {
    __newindex = function(t, k, v)
        if not map[k] then
            map[k] = v
        else
            error("try to assign a new value to a const var!!!")
        end
    end;
    __index = map
}

setmetatable(const, meta)